### ISSUE TITLE
Device Support

### ISSUE THREAD

**Issue by MikeDean2367** [NVIDIA/NeMo-Megatron-Launcher#6]
Thank you for coming up with this framework and I'm very interested in this framework. Would like to ask whether it supports V100, 3090?

**Comment by dimapihtar** [comment]
Hi,
no, it only supports A100 40/80GB.

**Comment by yaoyu-33** [comment]
Hi, we officially support A100 40/80GB. But with tweaks, it should also be able to run on V100 machines. The main change is that `precision` should be `16` or `32` and `megatron_amp_O2` should always be `False`.
3090 should support `bf16` as well, but since it has less memory, please tune down MBS and take advantage of activation checkpointing.
If you see issues running, considering turning off the fusion arguments.

**Comment by MikeDean2367** [comment]
> Hi, we officially support A100 40/80GB. But with tweaks, it should also be able to run on V100 machines. The main change is that `precision` should be `16` or `32` and `megatron_amp_O2` should always be `False`. 3090 should support `bf16` as well, but since it has less memory, please tune down MBS and take advantage of activation checkpointing. If you see issues running, considering turning off the fusion arguments.

OK. Thank you for your reply.

**Comment by MikeDean2367** [comment]
> Hi, no, it only supports A100 40/80GB.

OK. Thank you for your reply.

**Comment by MikeDean2367** [comment]
I will try it later
